# vim: ft=dockerfile
FROM redhat/ubi8

RUN dnf install openssl-devel clang compiler-rt cmake -y
RUN curl -sSL sh.rustup.rs >/tmp/rustup.sh && bash /tmp/rustup.sh -y --profile complete
RUN . /root/.cargo/env && cargo install cargo-generate-rpm
